
services:
  web:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app1_db
      POSTGRES_USER: app1_user
      POSTGRES_PASSWORD: app1_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: