
services:
  api:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    command: npm start
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: